#ifndef REWARD_NAME_ENUM_H
#define REWARD_NAME_ENUM_H

enum reward_name {
    CHAMPIONS_LEAGUE_FINAL_TICKET,
    KARAOKE_PRO_MICROPHONE,
    PIRATES_OF_THE_CARIBBEAN_COLLECTION
};

#endif // REWARD_NAME_ENUM_H
